# GettingData-Codebook
#### _Chris Vennes_
#### _August 22, 2015_


This codebook contains details on variables found in my TidyData output of run_analysis.R.  

### NOTES FROM DATASET:
The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

### TIDY DATA MEASURES
For each variable outside of Subject and Activity.Name there are data points for both Mean (Mean Value) and StD (Standard Deviation) these are averaged for all tests from that subject on the particular activity.

Variable              | Measure  |  Description
--------              | -------  |  ------------
Subject               | N/A      |  Number indicating the subject of the activity
Activity.Name         | N/A      |  Name of activity subject performed during test
tBodyAcc              | Mean/STD |  Mean of all records on that activity & subject
tGravityAcc           | Mean/STD |  Mean of all records on that activity & subject
tBodyAccJerk          | Mean/STD |  Mean of all records on that activity & subject
tBodyGyro             | Mean/STD |  Mean of all records on that activity & subject
tBodyGyroJerk         | Mean/STD |  Mean of all records on that activity & subject
tBodyAccMag           | Mean/STD |  Mean of all records on that activity & subject
tGravityAccMag        | Mean/STD |  Mean of all records on that activity & subject
tBodyAccJerkMag       | Mean/STD |  Mean of all records on that activity & subject
tBodyGyroMag          | Mean/STD |  Mean of all records on that activity & subject
fBodyAcc              | Mean/STD |  Mean of all records on that activity & subject
fBodyGyro             | Mean/STD |  Mean of all records on that activity & subject
fBodyAccMag           | Mean/STD |  Mean of all records on that activity & subject
fBodyBodyAccJerkMag   | Mean/STD |  Mean of all records on that activity & subject
fBodyBodyGyroJerkMag  | Mean/STD |  Mean of all records on that activity & subject
